# Generated by Django 4.2.30 on 2026-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="Updated_on",
            new_name="updated_on",
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
