# Generated by Django 6.0.5 on 2026-06-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutapp", "0002_rename_updated_on_about_updated_on_alter_about_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
            ],
        ),
    ]
