# Generated by Django 6.0.5 on 2026-09-04 19:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutapp", "0003_collaboraterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
