# Generated by Django 6.0.5 on 2026-09-25 09:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutapp", "0004_about_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
